# Copyright (c) Henry van Merode.
# Licensed under the MIT License.

# Build numbering format
name: $(Date:yyyyMMdd)$(Rev:.r)

trigger: none

# Define 2 repositories, one is an Azre DevOps repo and the other a GitHub repo
# Note, that the 'endpoint' parameter is mandatory for a GitHub repository
resources:
  repositories:
    - repository: external
      name: Templates/Templates
      type: git
      ref: refs/heads/develop
    - repository: external2
      name: hvmerode/azdo-templates
      type: github
      endpoint: GitHubEndpoint

parameters:
  - name: param_1
    type: string
    default: 'contains a default value'
  - name: environment
    type: string
    default: dev
  - name: sleep
    type: string
    default: 1

variables:
  - name: myVar
    value: myValue
  - name: aws_connection
    value: 1234567890
  - name: aws_region
    value: us-east-1

stages:
  - template: templates/stages/template-stages.yml
    parameters:
      aNiceParam: param_1_value

  - stage: ExecuteScriptStage
    displayName: 'Execute script'
    condition: always()
    jobs:
      - job: Job_X
        displayName: Job XA
        pool:
          vmImage: 'ubuntu-latest'
        steps:
          - script: |
              echo 'This is a multiline script'
              echo 'Row 2 of that script'
            displayName: Step XA
      - job: Job_XB
        displayName: Job XB
        pool:
          vmImage: 'ubuntu-latest'
        steps:
          - script: |
              echo 'Job_2.Task_1'
            displayName: Step XB
          - template: templates/steps/template-steps.yml
            parameters:
              param_1: param_1_value
              param_2: param_2_value
      - job: Job_XC
        displayName: Job XC
        pool:
          vmImage: 'ubuntu-latest'
        steps:
          - template: test-template.yml@external
          - template: test-template.yml@external2
          - script: |
              echo 'Job_2.Task_3: Sleep some seconds'
              sleep ${{ parameters.sleep }};
            displayName: Step XC
      - template: templates/jobs/template-jobs.yml
        parameters:
          param_1: param_1_value

  - stage: DeployStage
    condition: eq(variables['Build.SourceBranchName'], 'master')
    displayName: 'DeployStage'
    jobs:
      - job: Job_XD
        displayName: Job XD
        pool:
          vmImage: 'ubuntu-latest'
        steps:
          - script: |
              echo 'AWS Connection is: $(aws_connection)'
              echo 'AWS Region is: $(aws_region)'
            displayName: Step XD
      - job: Job_XE
        displayName: Job XE
        pool:
          vmImage: 'ubuntu-latest'
        steps:
          - script: |
              echo 'Deploy to AWS'
            displayName: Step XE
          - task: AWSShellScript@1
            inputs:
              awsCredentials: $(aws_connection)
              regionName: $(aws_region)
              scriptType: 'inline'
              inlineScript: |
                #!/bin/bash
                set -ex
                export cdk=`find $(Pipeline.Workspace)/. -name 'cdk*.jar'`
                export app=`find $(Pipeline.Workspace)/. -name 'app*.jar'`

                echo "Deploying stack"
                cdk deploy --app '${JAVA_HOME_11_X64}/bin/java -cp $cdk com.org.app.Stack' \
                    -c env=${{ parameters.environment }} \
                    -c app=$app
                    --all \
                    --ci \
                    --require-approval never
            displayName: XF
