# Build numbering format
name: $(Date:yyyyMMdd)$(Rev:.r)

trigger: none

stages:
  - stage: PowershellMockStage
    jobs:
      - job: PowershellMockJob
        pool:
          vmImage: 'windows-latest'
        steps:
          - pwsh: |
              $Url = "https://server.contoso.com:8089/services/search/jobs/export"
              $Body = @{
                search = "search index=_internal | reverse | table index,host,source,sourcetype,_raw"
                output_mode = "csv"
                earliest_time = "-2d@d"
                latest_time = "-1d@d"
              }
              Invoke-RestMethod -Method 'Post' -Uri $url -Body $body -OutFile output.csv
            displayName: 'Invoke-RestMethod step'
