# Build numbering format
name: $(Date:yyyyMMdd)$(Rev:.r)

trigger:
  branches:
    include:
      - master
      - myFeature
    exclude:
      - releases/*

variables:
  - name: testVar
    value: test

stages:
  - stage: simpleStage
    jobs:
      - job: simpleJob
        pool:
          vmImage: 'ubuntu-latest'
        steps:
          - script: |
              echo 'This is a simple test'
            displayName: 'Testing, testing'
