parameters:
  - name: param_1
    type: string
    default: param_1_value

jobs:
  - job: TemplateJob_1
    pool:
      vmImage: 'ubuntu-latest'
    steps:
      - script: |
          echo 'This is job: TemplateJob_1 with parameter ${{ parameters.param_1 }}'