parameters:
- name: param_1
  type: string
  default: xxx
jobs:
- job: Job_A
  displayName: template-jobs.yml job
  variables:
    - name: jobVar
      value: 'jobVarInTemplate'
  pool:
    vmImage: ubuntu-latest
  steps:
  - script: |
      echo 'This is job: Job_A with parameter ${{ parameters.param_1 }}'
    displayName: template-jobs.yml script
  - template: ../steps/template-steps.yml
