parameters:
- name: aNiceParam
  type: string
  default: aNiceDefault
- name: template
  type: string
  default: "default_name_of_template_param"
stages:
- stage: Stage_B
  displayName: template-stages.yml stage
  jobs:
  - job: Job_B
    displayName: template-stages.yml job
    pool:
      vmImage: ubuntu-latest
    steps:
    - script: |
        echo 'This is job: Job_B with parameter ${{ parameters.aNiceParam }}'
      displayName: template-stages.yml script
  - template: ../jobs/template-jobs.yml
